//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOLStatsMango.Resources.en {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DOLStatsMango.Resources.en.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application uses several data sources from the Department Of Labor (DOL).   The Bureau of Labor Statistics Occupational Employment Statistics data can be found at http://developer.dol.gov/DOL-BLS2010-DATASET.htm.
        /// </summary>
        public static string About_DOLInfo {
            get {
                return ResourceManager.GetString("About_DOLInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestSharp is a simple, open source REST client for .NET designed primarily for consuming third-party HTTP APIs.  Created by John Sheeshan with contributions made by many more..
        /// </summary>
        public static string About_RestSharpInfo {
            get {
                return ResourceManager.GetString("About_RestSharpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://silverlight.codeplex.com
        ///Microsoft Public License (Ms-PL)
        ///© Copyright 2011 Microsoft Corporation.
        /// </summary>
        public static string About_SilverlightToolkit {
            get {
                return ResourceManager.GetString("About_SilverlightToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieval of your current location is aided by Yahoo Local Search..
        /// </summary>
        public static string About_YahooSearchInfo {
            get {
                return ResourceManager.GetString("About_YahooSearchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Zillow API, Zillow Data, and Zillow Brand &amp; Links are the property of Zillow, and subject to the intellectual property rights of Zillow and its licensors. (c) 2006-2009 Zillow, Inc. All rights reserved..
        /// </summary>
        public static string About_Zillow {
            get {
                return ResourceManager.GetString("About_Zillow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AhCygpp81ncJ7BbxZD1o3klZMtKWHXXDibsQmDx2oGhIVzzUA6Dn6Uj9gvruflPf.
        /// </summary>
        public static string BingMapsApiKey {
            get {
                return ResourceManager.GetString("BingMapsApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.careerbuilder.com/v1/.
        /// </summary>
        public static string CareerBuilderBaseUrl {
            get {
                return ResourceManager.GetString("CareerBuilderBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WDH50QY78HN4GCKZSD6M.
        /// </summary>
        public static string CareerBuilderDeveloperKey {
            get {
                return ResourceManager.GetString("CareerBuilderDeveloperKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Of Labor Disclaimer.
        /// </summary>
        public static string DOLDisclaimer_Heading {
            get {
                return ResourceManager.GetString("DOLDisclaimer_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE MATERIAL EMBODIED IN THIS SOFTWARE IS PROVIDED TO YOU &quot;AS-IS&quot; AND WITHOUT WARRANTY OF ANY KIND, EXPRESS, IMPLIED, OR OTHERWISE, INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT SHALL THE UNITED STATES DEPARTMENT OF LABOR (DOL) OR THE UNITED STATES GOVERNMENT BE LIABLE TO YOU OR ANYONE ELSE FOR ANY DIRECT, SPECIAL, INCIDENTAL, INDIRECT, OR CONSEQUENTIAL DAMAGES OF ANY KIND, OR ANY DAMAGES WHATSOEVER, INCLUDING WITHOUT LIMITATION, LOSS OF PROFIT, LOSS OF USE, SAV [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DOLDisclaimer_Text {
            get {
                return ResourceManager.GetString("DOLDisclaimer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Job Compass to access and use your location?.
        /// </summary>
        public static string LocationDisclaimer_Heading {
            get {
                return ResourceManager.GetString("LocationDisclaimer_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing this information helps us provide and improve our mapping and local search services.  We won&apos;t use this info to identify or contact you..
        /// </summary>
        public static string LocationDisclaimer_Text {
            get {
                return ResourceManager.GetString("LocationDisclaimer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow the app to use your current location.
        ///To turn off location for all apps on your phone, go to the Settings app of your Windows Phone..
        /// </summary>
        public static string Settings_LocationMessage {
            get {
                return ResourceManager.GetString("Settings_LocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55p4ekxvg2v64s2k9pjnvgae.
        /// </summary>
        public static string TruliaApiKey {
            get {
                return ResourceManager.GetString("TruliaApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1Gi7AprV34FVl9YbbzeN3ImhUbRLwqrS8LPBD7A7hNo_3NOLt0Mz8f1VhyPzgLcD.x2z.
        /// </summary>
        public static string YahooAppId {
            get {
                return ResourceManager.GetString("YahooAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dj0yJmk9WXlVSGE5UUk4OGpuJmQ9WVdrOVNubGtNa05tTTJVbWNHbzlNekE0TURZeU56WXkmcz1jb25zdW1lcnNlY3JldCZ4PTM4.
        /// </summary>
        public static string YahooConsumerKey {
            get {
                return ResourceManager.GetString("YahooConsumerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d5d42dfc4c85d3a273b532e27c8d423407f56c17.
        /// </summary>
        public static string YahooConsumerSecret {
            get {
                return ResourceManager.GetString("YahooConsumerSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://where.yahooapis.com/.
        /// </summary>
        public static string YahooPlaceFinderBaseUrl {
            get {
                return ResourceManager.GetString("YahooPlaceFinderBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Zillow, Inc., 2006-2011. Use is subject to Terms of Use..
        /// </summary>
        public static string Zillow_Disclaimer {
            get {
                return ResourceManager.GetString("Zillow_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Me Move®.
        /// </summary>
        public static string Zillow_MakeMeMove {
            get {
                return ResourceManager.GetString("Zillow_MakeMeMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See {0} Real Estate on Zillow.
        /// </summary>
        public static string Zillow_Neighborhood_Disclaimer {
            get {
                return ResourceManager.GetString("Zillow_Neighborhood_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zestimate®.
        /// </summary>
        public static string Zillow_Zestimate {
            get {
                return ResourceManager.GetString("Zillow_Zestimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X1-ZWz1d6xwzun5e3_4dboj.
        /// </summary>
        public static string ZillowApiKey {
            get {
                return ResourceManager.GetString("ZillowApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.zillow.com/webservice/.
        /// </summary>
        public static string ZillowBaseUrl {
            get {
                return ResourceManager.GetString("ZillowBaseUrl", resourceCulture);
            }
        }
    }
}
